"""add users table

Revision ID: 2330fb63ca33
Revises: 86dde3584a72
Create Date: 2026-09-02 00:08:58.642671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2330fb63ca33'
down_revision: Union[str, None] = '86dde3584a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('github_id', sa.String(), nullable=False),
    sa.Column('github_username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    # ### end Alembic commands ###
    # NOTE: autogenerate also wanted to drop ix_traces_input_embedding here - a
    # known false positive (it's a raw-SQL ivfflat index from the initial
    # migration, not tracked in SQLAlchemy metadata, see database-schema.md).
    # Removed from this migration; the index stays.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
