"""add llm provider and api key to projects

Revision ID: 25e6af1098ff
Revises: f3a1c9e7b2d4
Create Date: 2026-09-02 16:05:26.915835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25e6af1098ff'
down_revision: Union[str, None] = 'f3a1c9e7b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('llm_provider', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('llm_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'llm_api_key')
    op.drop_column('projects', 'llm_provider')
    # ### end Alembic commands ###
