"""add replay_method to impact_reports

Revision ID: 506765e43321
Revises: 25e6af1098ff
Create Date: 2026-09-02 16:08:57.444502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '506765e43321'
down_revision: Union[str, None] = '25e6af1098ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'impact_reports',
        sa.Column('replay_method', sa.String(), nullable=False, server_default='mock'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('impact_reports', 'replay_method')
    # ### end Alembic commands ###
