"""add github_repo to projects

Revision ID: 837e39de40e5
Revises: c204d8f71557
Create Date: 2026-09-02 14:13:42.901049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '837e39de40e5'
down_revision: Union[str, None] = 'c204d8f71557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_repo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_repo')
    # ### end Alembic commands ###
