"""initial schema

Revision ID: 86dde3584a72
Revises: 
Create Date: 2026-08-23 15:55:17.933421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '86dde3584a72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('input_price_per_1k', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('output_price_per_1k', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_table('agents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_clusters',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trace_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_clusters_project_id'), 'failure_clusters', ['project_id'], unique=False)
    op.create_table('agent_configs',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('prompt', 'model', name='agent_config_kind'), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('model_provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_proposals',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('baseline_config_id', sa.UUID(), nullable=False),
    sa.Column('candidate_config_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'analyzing', 'analyzed', 'shipped', name='change_proposal_status'), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['baseline_config_id'], ['agent_configs.id'], ),
    sa.ForeignKeyConstraint(['candidate_config_id'], ['agent_configs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_proposals_project_id'), 'change_proposals', ['project_id'], unique=False)
    op.create_table('traces',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('agent_config_id', sa.UUID(), nullable=False),
    sa.Column('trace_ref', sa.String(), nullable=False),
    sa.Column('workflow_tag', sa.String(), nullable=True),
    sa.Column('segment_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('input_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'error', name='trace_status'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('model_provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('live', 'replay', name='trace_source'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_ref')
    )
    op.create_index(op.f('ix_traces_agent_id'), 'traces', ['agent_id'], unique=False)
    op.create_index(op.f('ix_traces_project_id'), 'traces', ['project_id'], unique=False)
    op.create_index(op.f('ix_traces_workflow_tag'), 'traces', ['workflow_tag'], unique=False)
    op.create_table('evaluations',
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evaluator_type', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_trace_id'), 'evaluations', ['trace_id'], unique=False)
    op.create_table('failure_cluster_members',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['failure_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'trace_id')
    )
    op.create_table('impact_reports',
    sa.Column('change_proposal_id', sa.UUID(), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Enum('SHIP', 'MODIFY', 'BLOCK', name='impact_recommendation'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('overall_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('segment_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_proposal_id'], ['change_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_proposal_id')
    )
    op.create_table('prediction_outcomes',
    sa.Column('change_proposal_id', sa.UUID(), nullable=False),
    sa.Column('predicted_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction_error', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_proposal_id'], ['change_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_proposal_id')
    )
    op.create_table('spans',
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('span_type', sa.Enum('query_processing', 'retrieval', 'embedding', 'vector_search', 'reranking', 'llm', 'tool_call', 'citation_check', 'custom', name='span_type'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('span_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_span_id'], ['spans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    op.create_table('impact_evidence',
    sa.Column('impact_report_id', sa.UUID(), nullable=False),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('baseline_trace_id', sa.UUID(), nullable=False),
    sa.Column('replay_trace_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['impact_report_id'], ['impact_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replay_trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_evidence_impact_report_id'), 'impact_evidence', ['impact_report_id'], unique=False)
    op.create_table('regression_tests',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('impact_report_id', sa.UUID(), nullable=True),
    sa.Column('source_trace_id', sa.UUID(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_condition', sa.Text(), nullable=False),
    sa.Column('baseline_output', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'passed', 'failed', name='regression_test_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['impact_report_id'], ['impact_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regression_tests_project_id'), 'regression_tests', ['project_id'], unique=False)
    op.create_table('retrieval_events',
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_events_span_id'), 'retrieval_events', ['span_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_arguments', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_span_id'), 'tool_calls', ['span_id'], unique=False)
    # ### end Alembic commands ###

    # cohort-matching similarity index (see docs/architecture.md, Change Engine)
    op.execute(
        "CREATE INDEX ix_traces_input_embedding ON traces "
        "USING ivfflat (input_embedding vector_cosine_ops) WITH (lists = 100)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_traces_input_embedding")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_span_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_retrieval_events_span_id'), table_name='retrieval_events')
    op.drop_table('retrieval_events')
    op.drop_index(op.f('ix_regression_tests_project_id'), table_name='regression_tests')
    op.drop_table('regression_tests')
    op.drop_index(op.f('ix_impact_evidence_impact_report_id'), table_name='impact_evidence')
    op.drop_table('impact_evidence')
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_table('spans')
    op.drop_table('prediction_outcomes')
    op.drop_table('impact_reports')
    op.drop_table('failure_cluster_members')
    op.drop_index(op.f('ix_evaluations_trace_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_traces_workflow_tag'), table_name='traces')
    op.drop_index(op.f('ix_traces_project_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_agent_id'), table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_change_proposals_project_id'), table_name='change_proposals')
    op.drop_table('change_proposals')
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_failure_clusters_project_id'), table_name='failure_clusters')
    op.drop_table('failure_clusters')
    op.drop_table('agents')
    op.drop_table('projects')
    op.drop_table('organizations')
    op.drop_table('model_pricing')
    # ### end Alembic commands ###
