"""add github_access_token to users

Revision ID: c204d8f71557
Revises: 2330fb63ca33
Create Date: 2026-09-02 13:35:05.322702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c204d8f71557'
down_revision: Union[str, None] = '2330fb63ca33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_access_token')
    # ### end Alembic commands ###
